spring:
  application:
    name:  item-service
#配置端口
#server:
#  port: 8001
  
eureka:
  client:
    service-url:     #向3台eureka进行注册
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka, http://eureka3:2003/eureka
      
---
spring:
  profiles: item1
  
server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002
---
spring:
  profiles: item3

server:
  port: 8003