sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"


spring:
  application:
    name: user-service
    
#server:
#  port: 8101
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka,http://eureka3:2003/eureka

management:
  endpoints:
    web:
      exposure:   
        include: refresh   #动态配置刷新
---
spring:
  profiles: user1

server:
  port: 8101
---
spring:
  profiles: user2

server:
  port: 8102
---
spring:
  profiles: user3

server:
  port: 8103